version: "3.7"
services:
    reverseproxy:
        image: reverseproxy
        build: .
        container_name: reverseproxy
        ports:
            - 8001:8081
            - 8002:8082
        networks:
            - frontend
            - backend
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        container_name: nginx
        networks:
            - backend
        restart: always
 
    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        container_name: apache
        networks:
            - backend
        restart: always
networks:
  frontend:
  backend:

