version: "3.7"
services:
  guacamole:
    image: oznu/guacamole:armhf
    container_name: guacamole
    hostname: guacomole
    volumes:
      - postgres:/config
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
  postgres: