apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dkr-wol
  name: dkr-wol
spec:
  containers:
  - env:
    - name: WOLHTTPPORT
      value: "8082"
    image: local/go-rest-wol
    name: dkr-wol
    ports:
    - containerPort: 8082
      hostPort: 8082
      protocol: TCP
    resources: {}
  restartPolicy: OnFailure
status: {}
