apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dkr-wol
  name: dkr-wol
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    io.kompose.service: dkr-wol
status:
  loadBalancer: {}
